### ISSUE TITLE
apps.get_info does not return infoirmation about current instance id

### ISSUE THREAD

**Issue by tquiviger** [saagie/api-saagie#112]
apps.get_info does not return infoirmation about current instance id

This method should return a list of instances for a given app (with a max instance parameter, as it's done for the jobs and pipelines)

**Comment by saagie-service** [comment]
Trello card: [[#112] apps.get_info does not return infoirmation about current instance id](https://trello.com/c/X8Tb34iw)

**Comment by tquiviger** [comment]
In the Saagie UI, they are using instances(limit: 1, lastExecution: true)
