### ISSUE TITLE
Add the create or upgrade feature for jobs, pipelines and apps

### ISSUE THREAD

**Issue by tquiviger** [saagie/api-saagie#116]
For jobs, pipelines and apps, add a create_or_upgrade method that will check if a given job, app or pipeline already exists inside a project (based on its name) and decide if it needs to be created or updated

**Comment by saagie-service** [comment]
Trello card: [[#116] Add the create or upgrade feature for jobs, pipelines and apps](https://trello.com/c/f95HvdX9)
