### ISSUE TITLE
Add support for repository management

### ISSUE THREAD

**Issue by Andromelus** [saagie/api-saagie#120]
**Is your feature request related to a problem? Please describe.**
We us the repository functionnality to give customized images to the users of our platforme.

We would like to automate repository update, but there is no documented API on that and it is not available with this library.

**Describe the solution you'd like**

It would be nice if we could:

- Create a repository
- Update a repository

With this library.

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by saagie-service** [comment]
Trello card: [[#120] Ad support for repository management](https://trello.com/c/a6Kg5ehk)
