### ISSUE TITLE
When upgrading a job, if the `file` param has an absolute path, the job cannot be launched.

### ISSUE THREAD

**Issue by Andromelus** [saagie/api-saagie#121]
**Describe the bug**

Using the following:

```python
saagie.jobs.upgrade(
    job_id="3d3108f5-d0a1-4364-b704-5c21bce00260",
    runtime_version="3.9",
    command_line="echo \"toto\"",
    file="C:\\Users\\castelain.florianext\\.saagie\\tmp\\CICD-PLUGIN-TEST.zip"
)
```
The package looks like this in the UI:

![image](https://user-images.githubusercontent.com/10050024/176624377-2cfce58f-0e27-45e9-9c17-a5621600536d.png)

And Saagie is not able to launch the job:

![image](https://user-images.githubusercontent.com/10050024/176625966-44dfc61d-a4e5-4bf5-8661-584400a94010.png)

-----

However, when using this:

```python
saagie.jobs.upgrade(
    job_id="3d3108f5-d0a1-4364-b704-5c21bce00260",
    runtime_version="3.9",
    command_line="echo \"toto\"",
    file="./test/CICD-PLUGIN-TEST.zip"
)
```

The package looks like this:

![image](https://user-images.githubusercontent.com/10050024/176626501-a081747d-5b20-4b04-a710-3718a2a201c9.png)

And Saagie is able to launch the job.

**Expected behavior**

- Saagie should be able to  launch the job no matter the package name or
- This library should remone unnecessary content from the package name before upgrading the job (keep everything after the last chunk of the path for example)

```
$ pip list | grep saagie
saagieapi                          1.1.0
```

**Comment by guillaumeprevost76** [comment]
Hello,
This issue is corrected with release 2.6.1
Regards
