### ISSUE TITLE
What does `use_previous_artifact` mean and do ?

### ISSUE THREAD

**Issue by Andromelus** [saagie/api-saagie#125]
This is a question about the parameter `use_previous_artifact`, for [job upgrade](https://github.com/saagie/api-saagie/wiki/3----Jobs#upgrading-a-job).

What does it mean and what does it do ? 

A github search gave nothing relevant.

**Comment by saagie-service** [comment]
Trello card: [[#125] What does `use_previous_artifact` mean and do ?](https://trello.com/c/mcLEzBdQ)

**Comment by tquiviger** [comment]
Hi @Andromelus 

This parameter indicates whether : 
- you want to upload a new package for your new job version (use_previous_artifact=false)
- you want to keep the package of the existing job version and just update the command line for this new version for instance (use_previous_artifact=true)

**Comment by Andromelus** [comment]
Thanks.
It would be nice if this was written in the documentation.

**Comment by tquiviger** [comment]
Agreed, we'll try to improve our documentation with more details about each attribute.
