### ISSUE TITLE
saagieapi apps API is not compatible with newer versions of Saagie platform

### ISSUE THREAD

**Issue by TFellet** [saagie/api-saagie#132]
When using `saagie_api.apps.list_for_project_minimal` and `saagie_api.apps.list_for_project` on recently updated Saagie platforms, errors with the following message: "labWebApps operation is no longer supported. Use project instead."

**Comment by saagie-service** [comment]
Trello card: [[#132] saagieapi apps API is not compatible with newer versions of Saagie platform](https://trello.com/c/DHXKd8JR)
