### ISSUE TITLE
Update documentation for apps.get_info with Saagie 3.0.0

### ISSUE THREAD

**Issue by tquiviger** [saagie/api-saagie#140]
Starting from Saagie 3.0.0, apps.get_info does not return instances but events. Wiki should be updated accordingly.

**Comment by saagie-service** [comment]
Trello card: [[#140] Update documentation for apps.get_info with Saagie 3.0.0](https://trello.com/c/mo5wVqf1)

**Comment by Qiwei08** [comment]
The documentation has been updated
