### ISSUE TITLE
Create or update project environment variable when the variable's name is already used in a global environment variable

### ISSUE THREAD

**Issue by Qiwei08** [saagie/api-saagie#142]
**Describe the bug**
When we use the function ''env_vars.create_or_update_for_project", if the name of the variable is already used in a global environment variable, this function will try to update the variable and then it will raise an error: 

```
"TransportQueryError: {'message': 'Environment variable is invalid', 'path': ['saveEnvironmentVariable'], 'extensions': {'scope': 'A Global variable must
not be linked to an entity id', 'classification': 'ValidationError'}}"
```

**Expected behavior**
When the name of the variable is already used in a global environment variable, and we use the function  ''env_vars.create_or_update_for_project", it should create a project environment variable instead to update it. 

**Exemple to reproduce the error**

```
from saagieapi import SaagieApi
url_saagie = "https://saagie-workspace.prod.saagie.io"
id_platform = "4"
user = "XXX"
realm = "saagie"
pwd = "YYYY"
saagie_api = SaagieApi(
    url_saagie=url_saagie, id_platform=id_platform, user=user, password=pwd, realm=realm
)

saagie_api.env_vars.create_global(name="TEST_VAR1", value="1234")
project_id = "project_id_to_create_or_update_env_var"
saagie_api.env_vars.create_or_update_for_project(name="TEST_VAR1", value="2345", project_id=project_id)
```

**Comment by saagie-service** [comment]
Trello card: [[#142] Create or update project environment variable when the variable's name is already used in a global environment variable](https://trello.com/c/OmVogiIH)
