### ISSUE TITLE
Export app with versions_only_current=True, doesn't work

### ISSUE THREAD

**Issue by Qiwei08** [saagie/api-saagie#143]
**Describe the bug**
Export app with versions_only_current=True, doesn't work, because when getting app information, if we set versions_only_current=True, then we don't have the versions section in the response, then the following part of code doesn't work
```
for version in app_info["versions"]:
                version["runtimeContextLabel"] = self.get_runtime_label_by_id(
                    app_techno_id, version["runtimeContextId"]
                )
```

**Comment by saagie-service** [comment]
Trello card: [[#143] Export app with versions_only_current=True, doesn't work](https://trello.com/c/7dxSLkhe)
