### ISSUE TITLE
Cannot edit an app without alerting

### ISSUE THREAD

**Issue by Qiwei08** [saagie/api-saagie#144]
**Describe the bug**
When the app is created without alerting then we want to edit the app name, we get the following error:

```
RuntimeError: ❌ You must provide a status list and either an email or a login to enable the alerting
```

**Expected behavior**
it should work

**Comment by saagie-service** [comment]
Trello card: [[#144] Cannot edit an app without alerting](https://trello.com/c/vFXk3mkh)
