### ISSUE TITLE
When updating project, value of authorizedGroups is not updated

### ISSUE THREAD

**Issue by m0lekul** [saagie/api-saagie#159]
**Describe the bug**

When updating a project using "groups_and_roles" parameter in the Projects.edit function, the value of authorizedGroup is not updated.
authorizedGroups is set with the existing authorizations. 

When we use "group" + "role" parameter in the same function, the authorizedGroup is correctly set.
 
**Expected behavior**

The authorizedGroups  of project must be correctly set, when using "groups_and_roles" parameter.

**Comment by guillaumeprevost76** [comment]
Hello,

The correction is available in the version 2.2.8.

Regards
