### ISSUE TITLE
create_or_upgrade job

### ISSUE THREAD

**Issue by Qiwei08** [saagie/api-saagie#184]
We cannot use the function jobs.create_or_upgrade to upgrade correctly a job with an artefact, because the parameter use_previous_artefact is set to True at: https://github.com/saagie/api-saagie/blob/ff961c7a72592f669895c198ab4fb69a9a8d5a21/saagieapi/jobs/jobs.py#L628

**Comment by saagie-service** [comment]
Trello card: [[#184] create_or_upgrade job](https://trello.com/c/SZTMuFoc)

**Comment by guillaumeprevost76** [comment]
Corrected with release 2.6.1
