### ISSUE TITLE
PROPOSAL - run_with_callback should check on "UNKNOWN" status

### ISSUE THREAD

**Issue by Andromelus** [saagie/api-saagie#189]
`run_with_callback `currently only checks on these statuses:

`["SUCCEEDED", "FAILED", "KILLED"]`

However, as far as I know, the `"UNKNOWN"` status does not change into anything else (I, at least, never witnessed it). The consequence is that the function will wait until the reach of the timeout while it would have been faster to detect the `"UNKNOWN"` status.

https://github.com/saagie/api-saagie/blob/ffeab2d85aa6f5f8c0428858b86e41bd7fac5afc/saagieapi/jobs/jobs.py#L757C6-L757C62

If my assumption is correct (that the unknown status is a final state), could you ad this status into the checklist for `run_with_callback`?

**Comment by saagie-service** [comment]
Trello card: [[#189] PROPOSAL - run_with_callback should check on "UNKNOWN" status](https://trello.com/c/sao6qfLK)
