### ISSUE TITLE
Appel count_deletable_instances_by_date tronqué dans l'exemple donné

### ISSUE THREAD

**Issue by annelhomme** [saagie/api-saagie#201]
**Describe the bug**
Dans l'exemple de l'appel `count_deletable_instances_by_date` , c'est tronqué il manque "deletable". 
L'exemple indique `count_instances_by_date`

**Expected behavior**
que l'exemple corresponde à l'appel `count_deletable_instances_by_date`

**Comment by saagie-service** [comment]
Trello card: [[#201] Appel count_deletable_instances_by_date tronqué dans l'exemple donné](https://trello.com/c/CAc1Sq7e)

**Comment by guillaumeprevost76** [comment]
This issue is resolved in version 2.9.2 (PR: #202 )
