### ISSUE TITLE
Add the create App feature

### ISSUE THREAD

**Issue by tquiviger** [saagie/api-saagie#50]
Add the features for creating an app : 
- creating an app from a pre-configured app (mlflow, jupyter....)
- creating a custom app by entering docker information

**Comment by tquiviger** [comment]
Apparently Saagie uses the createJobMutation to create an App, see example below : 

`{
   "operationName":"createJobMutation",
   "variables":{
      "job":{
         "projectId":"8321e13c-892a-4481-8552-5be4b6cc5df4",
         "name":"Test MLflow",
         "description":"",
         "category":"",
         "technology":{
            "id":"d4beece1-3069-42bb-956f-4388c20fda78"
         },
         "isStreaming":false,
         "isScheduled":false,
         "storageSizeInMB":128
      },
      "jobVersion":{
         "dockerInfo":{
            "image":"saagie/mlflow-server:1.16-1.0"
         },
         "exposedPorts":[
            {
               "basePathVariableName":"SAAGIE_BASE_PATH",
               "isRewriteUrl":true,
               "isAuthenticationRequired":true,
               "port":5000,
               "name":"Mlflow Server"
            }
         ],
         "storagePaths":[
            
         ],
         "releaseNote":"",
         "resources":{
            "cpu":0.3,
            "disk":512,
            "memory":512
         }
      }
   },
   "query":"mutation createJobMutation($job: JobInput!, $jobVersion: JobVersionInput!) {\n  createJob(job: $job, jobVersion: $jobVersion) {\n    id\n    name\n    __typename\n  }\n}\n"
}`

**Comment by tquiviger** [comment]
With the App refactoring there are 2 versions of the API. Either we install an pre configured app : 

```
{
   "operationName":"installAppMutation",
   "variables":{
      "projectId":"60d4133b-c0bc-4e7e-bc5e-ea8ccce91122",
      "technologyId":"d4beece1-3069-42bb-956f-4388c20fda78",
      "contextId":"mlflow-server"
   },
   "query":"mutation installAppMutation($projectId: UUID!, $technologyId: UUID!, $contextId: String!) {\n  installApp(projectId: $projectId, technologyId: $technologyId, contextId: $contextId) {\n    id\n    name\n    __typename\n  }\n}\n"
}
```

or we create a custom app from scratch 
```
{
   "operationName":"createAppMutation",
   "variables":{
      "app":{
         "projectId":"60d4133b-c0bc-4e7e-bc5e-ea8ccce91122",
         "name":"zet",
         "description":"",
         "technologyId":"36912c68-d084-43b9-9fda-b5ded8eb7b13",
         "version":{
            "dockerInfo":{
               "image":"repo/image:v1"
            },
            "ports":[
               {
                  "number":"80",
                  "isRewriteUrl":true,
                  "basePathVariableName":null,
                  "scope":"PROJECT"
               }
            ],
            "releaseNote":"",
            "volumesWithPath":[
               
            ]
         }
      }
   },
   "query":"mutation createAppMutation($app: AppInput!) {\n  createApp(app: $app) {\n    id\n    __typename\n  }\n}\n"
}
```

**Comment by saagie-service** [comment]
Trello card: [[#50] Add the create App feature](https://trello.com/c/Iu5vtMWn)

**Comment by Qiwei08** [comment]
For the pre-configured app, the endpoint is available, but should wait the deployment of app v2 in order to use it.
