### ISSUE TITLE
Upgrade to gql 3.0

### ISSUE THREAD

**Issue by tquiviger** [saagie/api-saagie#52]
Upgrade to gql 3.0 that now supports file uploads (instead of using requests library)

**Comment by tquiviger** [comment]
https://gql.readthedocs.io/en/latest/usage/file_upload.html

**Comment by saagie-service** [comment]
Trello card: [[#52] Upgrade to gql 3.0](https://trello.com/c/loG73WJB)

**Comment by saagie-service** [comment]
Trello card: [[#52] Upgrade to gql 3.0](https://trello.com/c/SmNr1HcZ)
