### ISSUE TITLE
Refacto gql queries to use variables instead of string

### ISSUE THREAD

**Issue by JulienFrc** [saagie/api-saagie#53]
As in the doc of gql : https://gql.readthedocs.io/en/stable/usage/variables.html
We can use variables with $ instead of doing string.format()
See gql_create_graph_pipeline in gql_template for example

**Comment by saagie-service** [comment]
Trello card: [[#53] Refacto gql queries to use variables instead of string](https://trello.com/c/12voogAp)

**Comment by saagie-service** [comment]
Trello card: [[#53] Refacto gql queries to use variables instead of string](https://trello.com/c/k45sUfS4)
