### ISSUE TITLE
function edit_pipeline doesn't work when parameters changed

### ISSUE THREAD

**Issue by HugoPoupon** [saagie/api-saagie#63]
Impossible to launch the edit_pipeline function when one parameters changed between 2 versions of this pipeline.
Example : if we didn't set the "alerting" parameter in the first version of the pipeline and we set this parameter to None in the second version, the function doesn't work.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/57227254/154455083-b5e5328f-66d3-47d4-9403-ab35d5a9f8f9.png">

**Comment by saagie-service** [comment]
Trello card: [[#63] function edit_pipeline doesn't work when parameters changed](https://trello.com/c/ZwEm2IZP)
