### ISSUE TITLE
There is no way to know which version of saagieapi is compatible with which version of Saagie

### ISSUE THREAD

**Issue by Andromelus** [saagie/api-saagie#72]
**Is your feature request related to a problem? Please describe.**
Our platform got a breaking change in its API. I wanted to know which version of saagieapi I should use, but the release description does not specify which version of Saagie is compatible with the releases of saagieapi.

**Describe the solution you'd like**
In each release note, it should be specified which version(s) of Saagie is supported.
Additionnaly, saagieapi package should check directly with the Saagie platform if it is compatible.
For example, When creating an object from SaagieApi class, the init should query /version (or something similar) to check if the version of the API is handled by the package. If not, raise Exception with specific message.

**Comment by saagie-service** [comment]
Trello card: [[#72] There is no way to know which version of saagieapi is compatible with Saagie](https://trello.com/c/kOUqZNY8)

**Comment by guillaumeprevost76** [comment]
Hello,

We created a versioned documentation since version 2.3.0 accessible here : https://saagieapi.readthedocs.io/en/latest/ with a table of correspondance between SaagieAPI version and Saagie Platform version.
So we consider that is issue is not relevant anymore and close it.

Regards
