### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by tquiviger** [saagie/api-saagie#84]
To ensure maintainability of the current codebase, the following refactoring should be done 
- Remove the manager(V1) code
- All the code under projects should be moved directly under the saagieapi directory
- Code in the auth.py file should be put in saagieapi.py file
- Code regarding jobs, pipelines, projects should be separated by functionality, same for the gql queries. The new code structure would be something like : 
```
saagieapi
    saagie_api
    pipelines
        pipelines.py
        gql.py
    jobs
    apps
    projects
    env_vars
    docker_credentials
```
This would mean creating new classes for each main functionnality (pipelines, jobs...) that inherits the SaagieApi main class.
Let's take an example with the **create_job** function that would be now in the **jobs.py** file, and named **create** so that calling this function would mean calling **saagieapi.jobs.create**. The original **create_job** in saagieapi would be tagged as deprecated and will call the new function.

**Comment by saagie-service** [comment]
Trello card: [[#84] Refactoring](https://trello.com/c/HPwXScKQ)
